PROGS = gpio-int.c

COMMON_SRC = interrupt-asm.S

# if you need to override the install
BOOTLOADER = my-install

OPT_LEVEL = -O1
OPT_LEVEL = -O3
OPT_LEVEL = -Ofast

# our default optimization level.
OPT_LEVEL = -Og

# automatically run the code
RUN = 1

include $(CS340LX_2026_PATH)/libpi/mk/Makefile.robust-v3
